# seq_separator: ""
data_path:
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating

load_col: { inter: [user_id, item_id, rating] }
device: GPU

# model config
embedding_size: 64
hidden_size: 128
num_layers: 1
dropout_prob: 0.3
loss_type: CE

# eval_setting: TO_LS full
train_neg_sample_args: None
group_by_user: True
metrics: ["Recall", "MRR", "NDCG", "Hit", "Precision"]
topk: 10
metric_decimal_place: 5

learning_rate: 0.001
epochs: 20
train_batch_size: 512
eval_batch_size: 512
valid_metric: MRR@10
